services:
  # FastAPI web service
  - type: web
    name: steam-games-search-api
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: QDRANT_URL
        sync: false # Set this in the Render dashboard to your Qdrant Cloud URL
      - key: QDRANT_API_KEY
        sync: false # Set this in the Render dashboard to your Qdrant Cloud API key
      - key: COLLECTION_NAME
        value: steam_games_unique_20250302
      - key: CSV_FILE
        value: jan-25-released-games copy.csv
      - key: EMBEDDING_MODEL
        value: BAAI/bge-small-en-v1.5
      - key: SPARSE_MODEL
        value: prithivida/Splade_PP_en_v1
      - key: VECTOR_SIZE
        value: 384
      - key: BATCH_SIZE
        value: 100
      - key: RENDER
        value: "true"
      - key: KEEPALIVE_INTERVAL
        value: 240
